#sudo: required
# Yeah
language: c

services:
  - docker

before_install:
  - docker info
  - docker build -t dionakra/nodejs-java8 .

script:
  - docker run -it --rm dionakra/nodejs-java8 node -e "console.log(require('crypto').createHash('md5').update('test').digest('hex'))" | grep -q 098f6bcd4621d373cade4e832627b4f6
